name: tag

on:
  workflow_call:

jobs:
  build:
    name: call
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set version and tag...
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
