name: tag

on:
  workflow_call:

jobs:
  build:
    name: call
    runs-on: ubuntu-latest
    steps:
    - name: Checking out...
      uses: actions/checkout@v2
    - name: Setting git up...
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
    - name: Calculating new tag...
      run: |
        VERSION_PREFIX="v"
        VERSION_MAJOR_MINOR="1.0"
        VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
        
        if [ -z "$VERSION_PATCH" ]; then
          VERSION_PATCH=0
        else
          VERSION_PATCH=$((VERSION_PATCH + 1))
        fi
        
        NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"

        echo "tag=$NEW_TAG" >> $GITHUB_ENV
        echo "This version tag - $NEW_TAG"
    - name: Creating tag...
      if: env.tag
      run: |
        NEW_TAG=${{ env.tag }}
        git tag $NEW_TAG
    - name: Pushing tag...
      run: |
        git push origin $NEW_TAG
