---
        
name: Unity CI/CD - Release push (Format check, Test Runner, Build Runner)

on:
  push:
    branches: [ "release" ]
    
jobs:
  Unity_CICD_PR:
    runs-on: ubuntu-latest
    steps:
      - name: "Calling format check..."
        uses: ./.github/workflows/format.yaml
      - name: "Calling test runner..."
        uses: ./.github/workflows/test.yaml
      - name: "Calling build runner..."
        uses: ./.github/workflows/build.yaml
