name: tests

on:
  workflow_call:
    inputs:
      license:
        required: true
        type: string
      email:
        required: true
        type: string
      password:
        required: true
        type: string

jobs:
  tests:
    name: call
    runs-on: ubuntu-latest
    steps:
      - name: Checking out...
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Caching Library...
        uses: actions/cache@v3
        with:
          path: projekt/Library
          key: Library-projekt
          restore-keys: |
            Library-
      - name: Running tests... 
        uses: game-ci/unity-test-runner@v4
        id: tests
        env:
          UNITY_LICENSE: ${{ inputs.license }}
          UNITY_EMAIL: ${{ inputs.email }}
          UNITY_PASSWORD: ${{ inputs.password }}
        with:
          projectPath: projekt
          testMode: editmode
          artifactsPath: editmode-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Test results
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*'
      - uses: actions/upload-artifact@v3
        name: Uploading artifacts...
        if: always()
        with:
          name: Test results - artifacts
          path: ${{ steps.tests.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v3
        name: Uploading coverage...
        if: always()
        with:
          name: Coverage results - coverage
          path: ${{ steps.tests.outputs.coveragePath }}
