name: tests

on:
  workflow_call:

jobs:
  tests:
    name: call
    runs-on: ubuntu-latest
    steps:
      - name: Checking out...
        uses: actions/checkout@v2
      - name: Creating LFS files list...
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restoring LFS cache...
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
      - name: Git LFS pulling...
        run: |
          git lfs pull
          git add .
          git reset --hard
      - name: Restoring Library cache...
        uses: actions/cache@v2
        with:
          path: projekt/Library
          key: Library-test-project
          restore-keys: |
            Library-test-
      - name: Running tests...
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: projekt
          githubToken: ${{ secrets.TOKEN }}
